[RFC][UN-6690] Fabricator style guide
uniplaces/uniplaces-uniq-wiki pull request #4
Opened 2016-11-11 10:25 UTC by asantos00

https://uniplaces.atlassian.net/browse/UN-6690

2016-11-15 11:47 UTC, mmelo requested changes
@asantos00 reviewed

2016-11-15 11:47 UTC, mmelo commented on .gitignore
> +src/assets/uniq
delete .DS_Store file and add it to .gitignore list

2016-11-15 11:47 UTC, mmelo commented on bower.json
> +    "Luke Askew"
wrong! 👀

2016-11-15 11:47 UTC, mmelo commented on package.json
> +  "author": "Luke Askew",
nop 👀

2016-11-15 11:47 UTC, mmelo commented on package.json
> +  "name": "fabricator",
`"name": "uniq-wiki"`

2016-11-15 11:47 UTC, mmelo commented on src/data/uniq.json
> +    "available-at-github" : "The code is available at "
add missing link here please: https://github.com/uniplaces/uniplaces-uniq

2016-11-15 11:47 UTC, mmelo commented on src/materials/components/inputs/001-basic.html
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/materials/components/inputs/002-basic-error.html
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/materials/components/inputs/003-basic-warning.html
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/materials/components/inputs/004-basic-success.html
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/materials/components/inputs/02-bordered.html
> +
remove extra line at top

2016-11-15 11:47 UTC, mmelo commented on src/materials/components/inputs/04-price.html
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/materials/components/inputs/05-right-icon-error.html
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/materials/components/inputs/05-right-icon-success.html
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/materials/components/inputs/05-right-icon-warning.html
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/materials/components/inputs/05-right-icon.html
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/materials/components/pills/pill-error.html
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/materials/components/pills/pill-info.html
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/materials/components/pills/pill-success.html
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/materials/components/pills/pill-warning.html
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/materials/components/radio-button/radio-button.html
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/materials/components/textarea/textarea.html
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/materials/components/toggle/toggle.html
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/views/index.html
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on gulpfile.js
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on gulpfile.js
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on gulpfile.js
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on gulpfile.js
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on gulpfile.js
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on gulpfile.js
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on gulpfile.js
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on gulpfile.js
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/assets/toolkit/styles/alert.scss
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/assets/toolkit/styles/alert.scss
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/assets/toolkit/styles/animation.scss
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/assets/toolkit/styles/animation.scss
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/assets/toolkit/styles/buttons.scss
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/assets/toolkit/styles/colors.scss
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/assets/toolkit/styles/dropdown.scss
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/assets/toolkit/styles/input.scss
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/assets/toolkit/styles/header.scss
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/assets/toolkit/styles/input.scss
> +
remove extra lines

2016-11-15 11:47 UTC, mmelo commented on src/assets/toolkit/styles/messages.scss
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/assets/toolkit/styles/progress-bar.scss
> +
remove extra lines

2016-11-15 11:47 UTC, mmelo commented on src/assets/toolkit/styles/toolkit.scss
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/assets/toolkit/styles/toolkit.scss
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/assets/toolkit/styles/typography.scss
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/data/toolkit.yml
> +
remove extra lines

2016-11-15 11:47 UTC, mmelo commented on src/materials/components/animations/slide-in.html
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/materials/components/buttons/011-button-secondary.html
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/materials/components/buttons/012-button-alternative.html
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/materials/components/buttons/013-button-disabled.html
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/materials/components/buttons/014-button-upercase.html
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/materials/components/checkbox/checkbox.html
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/materials/components/checkbox/checkbox.html
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/materials/components/footer/footer.html
> +
remove extra line

2016-11-15 11:47 UTC, mmelo commented on src/materials/components/header/header.html
> +
remove extra line

2016-11-15 11:52 UTC, asantos00 commented on bower.json
> +    "Luke Askew"
I've asked for you yo review this PR right before I fixed it, sorry

2016-11-16 11:44 UTC, mmelo approved these changes

2016-11-16 11:44 UTC, merged